spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myqq?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/java #重启目录
#    freemarker:
#      cache: false    #页面不加载缓存，修改即时生效
server:
  port: 9431
#  配置最大头文件大小
#  max-http-header-size: 404857600

redis:
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  jedis:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池中的最小空闲连接
      max-idle: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 100000
  # 连接超时时间（毫秒）
  timeout: 5000
  #默认是索引为0的数据库
  database: 0

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: xc_satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
